### ISSUE TITLE
Review code and suggest changes on code

### ISSUE THREAD

**Issue by bpaniagua** [talmazov/SlicerPano#1]
@pieper @vovythevov @cdeepakroy

Could you please review @talmazov's code and make specific suggestions on what functions from what libraries should be best used in the algorithms to facilitate integration with slicer?

Thanks,
Bea

**Comment by pieper** [comment]
Hi @talmazov 

Since you have a handle on python, it would be good for you to try your hand at vtkpython and Qt via PythonQt

There's a lot of good material you might start with tutorials from these links to get familiar:

https://github.com/PerkLab/PerkLabBootcamp

https://www.slicer.org/wiki/Documentation/4.10/Training#Developing_and_contributing_extensions_for_3D_Slicer

Within Slicer, you can look in particular at the transforms infrastructure, and also how that makes use of the underlying classes in VTK and Slicer.

https://www.slicer.org/wiki/Documentation/Nightly/Modules/Transforms

https://vtk.org/doc/nightly/html/classvtkAbstractTransform.html

https://github.com/Slicer/Slicer/blob/master/Libs/vtkAddon/vtkOrientedGridTransform.h

Lots of material, but it's superpowerful once you get the hang of it.

**Comment by talmazov** [comment]
Hey Steve,
Can you point me in some direction about how Slicer uses the 4x4 vtk matrix? Rows and columns correspond to what when used for the RAS coordinate system? 

Thanks!

- Georgi

**Comment by pieper** [comment]
Hi Georgi - 

This page should give you everything you need: https://www.slicer.org/wiki/Coordinate_systems

Let me know if you have any questions,
Steve
